# --- SyHub Configuration ---
# Ensure 2-space indentation. Quote values starting with special characters like '!'

project:
  name: plantomio            # Project name, used in dashboard title etc.
  metrics_prefix: plnt_  # Prefix for metrics in VictoriaMetrics

hostname: plantomio.local     # mDNS hostname for accessing services (.local suffix)

# --- System Setup ---
# system_user: Automatically detected from user running 'sudo ./setup.sh'
# base_dir: Automatically set to /home/<system_user>/syhub
log_file: ./log/syhub_setup.log # Path for the setup script's detailed log
backup_directory: backups     # Relative to base_dir for config/data backups

# --- Service Names ---
service_names:
  mosquitto_conf: mqtt_config  # Name for Mosquitto config file
  nginx_site: plantomio    # Name for Nginx site config
  flow_id: plantomio-flow           # Node-RED flow ID

# --- Network Configuration ---
# Set to false to skip AP+STA setup entirely (e.g., if using Ethernet or manual config)
configure_network: true

# --- WiFi Access Point (AP) + Station (STA) Mode ---
# AP SSID and password will use project name if not specified
#setup guide: https://community.element14.com/products/raspberry-pi/f/forum/53996/configuring-a-wifi-access-point-using-raspberry-pi-how-to-with-the-new-kernel
wifi:
  ap_interface: uap0
  ap_ip: 192.168.77.1
  ap_subnet_mask: 255.255.255.0
  ap_dhcp_range_start: 192.168.77.100
  ap_dhcp_range_end: 192.168.77.150
  ap_dhcp_lease_time: 12h
  ap_ssid: auto              # Will use project_name + "_ap" if set to "auto"
  ap_password: auto          # Will use project_name + "123" if set to "auto"
  country_code: "DE"         # Set this to your country code
  sta_ssid: ""               # Your WiFi network SSID
  sta_password: ""           # Your WiFi network password

# --- MQTT Broker (Mosquitto) ---
# Credentials will use project name if not specified
mqtt:
  port: 1883
  username: plantomioX1             # Will use project_name if set to "auto"
  client_id_base: plantomioX1       # Will use project_name if set to "auto"
  password: plantomioX1Pass            # Will use project_name + "Pass" if set to "auto"
  topic_telemetry: "v1/devices/me/telemetry"

# --- Time Series Database (VictoriaMetrics) ---
victoria_metrics:
  version: v1.115.0
  port: 8428
  data_directory: /var/lib/victoria-metrics
  retention_period: 1y
  service_user: victoriametrics
  service_group: victoriametrics

# --- Data Processing (Node-RED) ---
node_red:
  port: 1880
  memory_limit_mb: 256
  username: "admin"
  password_hash: "$2b$08$W99V1mAwhUg5M9.hX6kjY.qtLHyvk1YbiXIMQ8T.xafDsGHNEa1Na"

# --- Web Dashboard (Flask + Gunicorn) ---
dashboard:
  port: 5000
  workers: 4

# --- Node.js Installation ---
nodejs:
  install_version: "lts" 